[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["pinkkoala95 <emma.keeley@madetech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
